name: dadeul

version: 1.0.1+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.2
  url_launcher: ^6.1.0

flutter:
  uses-material-design: true
