name: dadeul

version: 1.0.0+5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.13
  url_launcher: ^5.1.2

flutter:
  uses-material-design: true
